### ISSUE TITLE
learner.py Word dropout

### ISSUE THREAD

**Issue by TheElephantInTheRoom** [datquocnguyen/jPTDP#1]
Seems in lines 252-259 of learner.py, you still consider the character embeddings while the word is  potentially dropped. Not sure if this makes sense.

**Comment by datquocnguyen** [comment]
Why not? When it comes to unknown/unseen words, you still can definitely compute their character-based word representations!

**Comment by TheElephantInTheRoom** [comment]
Well, I think these are two separate things. If a word is unknown/rare then the character-based representation is certainly useful. But, if your random decision for dropping words have decided to ignore a word, then I can't see why this is called "dropout" if you still consider the character-level representation of the word that is dropped.
