### ISSUE TITLE
trainer.update

### ISSUE THREAD

**Issue by TheElephantInTheRoom** [datquocnguyen/jPTDP#2]
The trainer.update [here](https://github.com/datquocnguyen/jPTDP/blob/e36a9e237650066e9f9e0033e3f799a36efb3069/learner.py#L350) doesn't make sense. 

This was trainer.update_epoch() in the original code-base of bist-parser, but since the port from Dynet v1.1 to Dynet v2, the update_epoch function is deprecated. The use for calling update_epoch was to update the learning_rate. Which is not going to happen by calling trainer.update, as far as I know.

**Comment by datquocnguyen** [comment]
Right. You might want to comment that line when using the code. Thanks.
