### ISSUE TITLE
 Low UAS and LAS scores

### ISSUE THREAD

**Issue by Eugen2525** [datquocnguyen/jPTDP#4]
I have tried using your parser to test with EWT English treebank, and surprisingly UAS and LAS scores are low, around 87.50 and 84.53. I have used conll2017 shared task pretrained word embeddings. Do you think this is normal or am I doing something wrong?

**Comment by datquocnguyen** [comment]
It is normal. I also obtained similar scores on English EWT treebank. You might want to tune hyper-parameter to get better performance, rather than using default ones.
