### ISSUE TITLE
Named Entity Recognition tool ?! 

### ISSUE THREAD

**Issue by Raki22** [datquocnguyen/jPTDP#5]
Salutation Sir... 
that was a great job and a very powerful PoS tool 
I wanted to ask you if you developed a "named entity recognition" or as they name it "chunking" tool 
with this PoS tool. I need it in my experiments  
thanks in advance

**Comment by datquocnguyen** [comment]
Hi, I have a tool for joint NER and relation classification, available at https://github.com/datquocnguyen/jointRE But it might not suit your need. You might want to look at pure NER tools at https://github.com/jiesutd/NCRFpp or https://github.com/UKPLab/emnlp2017-bilstm-cnn-crf
