### ISSUE TITLE
Low POS in WSJ

### ISSUE THREAD

**Issue by ava-YangL** [datquocnguyen/jPTDP#6]
Hi , I tested on the WSJ dataset with model256 and only got accuracy about 95.5%.  I would like to ask that how can i get the accuracy 97.97 of the paper. 
I used the parameters set in the code, no changes were made.

**Comment by datquocnguyen** [comment]
You are using Python 2.7 & DyNet 2.0.3, aren't you ? 
(Also, the Stanford conversion toolkit v3.3.0 to obtain the data ? ) 
What is the parsing accuracy you get ?

**Comment by ava-YangL** [comment]
Thank you for your reply.
The version of Python and DyNet is right. But i didn't use Stanford conversion toolkit.
I just want to get the result of POS tagging,  do I also need to use the Stanford Toolkit in this case?

**Comment by datquocnguyen** [comment]
No, you do not really need using the Stanford conversion toolkit. Note that for model256, the POS tags used are PTB POS tags, not UPOS tags.

But, using data produced by the Stanford conversion toolkit would help you evaluating the predicted output properly (and easier). I am pretty confident that you can reproduce the reported scores in this manner (I already tested/rerun few times the trained model before releasing it).
